# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o0OAdh2lbnqZ-NDN_0pWPOqCUc9ndcaQ
"""



import streamlit as st
import pickle
import numpy as np

# Load the Stacking Classifier model and scaler
with open('stacking_clf.pkl', 'rb') as file:  # Replace with actual file name
    model = pickle.load(file)

with open('scaler.pkl', 'rb') as file:
    scaler = pickle.load(file)

# Title of the app
st.title("Credit Card Fraud Detection")
st.write("""
### Welcome to the Credit Card Fraud Detection App
This tool allows you to predict whether a credit card transaction is fraudulent or not, based on certain transaction features.
### How to Use:
- Enter the transaction details in the fields below.
- Click the 'Predict' button to check if the transaction is potentially fraudulent.
""")

# Input fields for the transaction features
amount = st.number_input("Transaction Amount", min_value=0.0, format="%.2f")
time = st.number_input("Transaction Time", min_value=0.0, format="%.2f")
v4 = st.number_input("V4 Feature", min_value=-5.0, max_value=5.0, format="%.2f")

# Button for prediction
if st.button("Predict"):
    features = np.array([[amount, time, v4]])  # Include all necessary features
    scaled_features = scaler.transform(features)
    prediction = model.predict(scaled_features)

    if prediction[0] == 1:
        st.error("Warning: Fraudulent transaction detected!")
    else:
        st.success("This transaction is not fraudulent.")

# Run the Streamlit app and expose it with ngrok
from pyngrok import ngrok

# Set up ngrok tunnel
public_url = ngrok.connect(port='8501')
print(f"Streamlit app will be accessible at: {public_url}")

# Run the Streamlit app
!streamlit run app.py &>/dev/null&